services:
  landing:
    image: ghcr.io/005-bot/landing:latest
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.landing.rule=Host(`xn--005-ddd9dya.xn--p1ai`)"
        - "traefik.http.routers.landing.entrypoints=https"
        - "traefik.http.routers.landing.tls=true"
        - "traefik.http.services.landing.loadbalancer.server.port=80"
      replicas: 1
      resources:
        reservations:
          memory: 8M
        limits:
          memory: 16M
      update_config:
        order: start-first
        monitor: 5s
        failure_action: rollback
      rollback_config:
        order: start-first
        monitor: 5s
        
networks:
  public:
    external: true
